---
- collection: &Backend.Civilizations.AntaranSettings
    items:
      - key: antaran_default_settings
        ANTARAN_DESIRED_VICTORY_CHANCES: 60
        ANTARAN_DESIRED_VICTORY_CHANCES_TOLERANCE: 5
        GRUDGE_FACTOR: .15

        ANTARAN_ATTACK_SPAWN_PORTAL_MIN_DISTANCE: 2
        ANTARAN_ATTACK_SPAWN_PORTAL_MAX_DISTANCE: 4

        ANTARANS_TURNS_TO_FIRST_MIN: 100
        ANTARANS_TURNS_TO_FIRST_MAX: 150
        ANTARANS_TURNS_TO_NEXT_MIN: 5
        ANTARANS_TURNS_TO_NEXT_MAX: 50

        ANTARAN_FRIGATE_SHIP_BLUEPRINT_TEMPLATE: design_frigate_antaran_5x
        ANTARAN_DESTROYER_SHIP_BLUEPRINT_TEMPLATE: design_destroyer_antaran_5x
        ANTARAN_CRUISER_SHIP_BLUEPRINT_TEMPLATE: design_cruiser_antaran_5x
        ANTARAN_BATTLESHIP_SHIP_BLUEPRINT_TEMPLATE: design_battleship_antaran_5x
        ANTARAN_TITAN_SHIP_BLUEPRINT_TEMPLATE: design_titan_antaran_5x
        ANTARAN_DOOMSTAR_SHIP_BLUEPRINT_TEMPLATE: design_doomstar_antaran_5x

        ANTARAN_ATTACK_MIN_FRIGATES: 2
        ANTARAN_ATTACK_MIN_DESTROYERS: 0
        ANTARAN_ATTACK_MIN_BATTLESHIPS: 0
        ANTARAN_ATTACK_MIN_CRUISERS: 0
        ANTARAN_ATTACK_MIN_TITANS: 0
        ANTARAN_ATTACK_MIN_DOOMSTARS: 0

        ANTARAN_FRIGATE_CHANCES: 35
        ANTARAN_DESTROYER_CHANCES: 37
        ANTARAN_CRUISER_CHANCES: 15
        ANTARAN_BATTLESHIP_CHANCES: 8
        ANTARAN_TITAN_CHANCES: 5
        ANTARAN_DOOMSTAR_CHANCES: 0

        ANTARAN_ATTACK_MAX_FRIGATES: 20
        ANTARAN_ATTACK_MAX_DESTROYERS: 30
        ANTARAN_ATTACK_MAX_BATTLESHIPS: 50
        ANTARAN_ATTACK_MAX_CRUISERS: 40
        ANTARAN_ATTACK_MAX_TITANS: -1
        ANTARAN_ATTACK_MAX_DOOMSTARS: 1

        ANTARAN_DEFENSE_MIN_FRIGATES: 24
        ANTARAN_DEFENSE_MIN_DESTROYERS: 16
        ANTARAN_DEFENSE_MIN_BATTLESHIPS: 4
        ANTARAN_DEFENSE_MIN_CRUISERS: 6
        ANTARAN_DEFENSE_MIN_TITANS: 2
        ANTARAN_DEFENSE_MIN_DOOMSTARS: 1

        ANTARAN_SPAWN_PORTAL_PREFAB_PATH: "sample"

        ANTARAN_SHIP_MODULE_DRIVE_KEY: shipmodule_antaran_drive
        ANTARAN_SHIP_MODULE_BIOLOGICAL_BOMB_KEY: shipmodule_chromodynamic_bomb
        ANTARAN_SHIP_MODULE_MISSILE_KEY: shipmodule_quantum_missile
        ANTARAN_SHIP_MODULE_TORPEDOE_KEY: shipmodule_plasma_torpedoes
        ANTARAN_SHIP_MODULE_BEAM_KEY: shipmodule_death_ray
        ANTARAN_SHIP_MODULE_CANNON_KEY: shipmodule_disruptor_cannon
        ANTARAN_SHIP_MODULE_ARMOR_KEY: shipmodule_xentronium_armor
        ANTARAN_SHIP_MODULE_COMPUTER_KEY: shipmodule_moleculartronic_computer
